#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "eric-oss-sample-pme-client.fullname" . }}
  labels:
  {{- include "eric-oss-sample-pme-client.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-sample-pme-client.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-sample-pme-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.apiGateway.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.pmserver.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  policyTypes:
    - Ingress
{{- end }}